### ISSUE TITLE
Substitution does not always avoid variable capture

### ISSUE THREAD

**Issue by paul-wild** [jzbor/lash#1]
The current strategy for capture avoidance does not always work correctly. A relatively small example is the following, which applies the Church numeral 2 to itself:

```
[λ] !vnormalize ((\f x. f (f x)) (\f x. f (f x)))
(\f . \x . f (f x)) (\f . \x . f (f x))
\x . (\f . \x . f (f x)) ((\f . \x . f (f x)) x)
\x . (\f . \x . f (f x)) (\x' . x (x x'))
\x . \x . (\x' . x (x x')) ((\x' . x (x x')) x)
\x . \x . (\x' . x (x x')) (x (x x))
\x . \x . x (x (x (x x)))
```

After the third step, the variable `x` that is bound by the outer `\x` gets captured by the inner `\x`, when instead it would be correct to rename the inner `\x` to some fresh variable name.

Similar issues arise for other pairs of Church numerals.

**Comment by jzbor** [comment]
Hi, thanks for the hint. It should be fixed now :)
